### ISSUE TITLE
Didn't work on a mac.

### ISSUE THREAD

**Issue by squaresurf** [asdf-community/asdf-clojure#1]
I tried to install clojure version 1.9.0, then follow this quickstart: https://clojurescript.org/guides/quick-start#node.js-repl

Unfortunately I did not have a `clj` command. I uninstalled this plugin and installed via `brew install clojure` and was off to the races.

p.s. I'm sorry if I just made a n00b mistake. I'm new to clojure, but :heart: `asdf`!

**Comment by halcyon** [comment]
I tried with clojure version `1.9.0` and didn't have any luck either. I have a non-asdf installation of `clojure` on a different linux system to compare it against, and when I run `clojure -e '(clojure-version)'` the output is "1.9.0".

However, when using asdf I see the following:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
.
.
.
Caused by: java.io.FileNotFoundException: Could not locate clojure/spec/alpha__init.class or clojure/spec/alpha.clj on classpath.
```

**Comment by halcyon** [comment]
I attempted to create a PR to resolve this, but soon found things have changed a lot since the official release of clojure 1.9.0. This results in a very different approach which made sense to rewrite from scratch - https://github.com/halcyon/asdf-clojure. I'm new to `asdf` and would really appreciate feedback from someone with asdf experience like @vic.

**Comment by squaresurf** [comment]
I only have asdf experience as a user or I would offer my help. Once your version works, would you post here as well as open a PR on the asdf plugins repo to replace this repos recommendation as it no longer works?

**Comment by halcyon** [comment]
@squaresurf It's been merged on the asdf plugins repo.

**Comment by squaresurf** [comment]
Thank you.

**Comment by smorimoto** [comment]
​Fixed in the latest master.
